services:
  - type: web
    name: lava-api
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && npm start
    envVars:
      - key: AI_API_KEY
        sync: false
      - key: AI_BASE_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: NODE_ENV
        value: production
