plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "G:\\我的项目\\lava-1\\web-preview\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "G:\\我的项目\\lava-1\\web-preview"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]