import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Share,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation } from '@react-navigation/native';
import { Header } from '../components/Header';
import { HospitalCard } from '../components/Card';
import { Button } from '../components/Button';
import { colors, typography, spacing, borderRadius } from '../constants/theme';
import { useGuideStore } from '../store';

export const GuideDisplayScreen: React.FC = () => {
  const navigation = useNavigation();
  const { currentGuide } = useGuideStore();

  const handleShare = async () => {
    try {
      await Share.share({
        message: `Check out my medical travel guide for ${currentGuide?.city}! Generated by LAVA App.`,
        title: 'LAVA Medical Travel Guide',
      });
    } catch (error) {
      console.error(error);
    }
  };

  const handleDownload = () => {
    // In a real app, this would generate and download a PDF
    alert('PDF download feature coming soon!');
  };

  if (!currentGuide?.content) {
    return (
      <SafeAreaView style={styles.container}>
        <Header
          showBack
          onBack={() => navigation.goBack()}
          title="Guide"
        />
        <View style={styles.emptyContainer}>
          <Text style={styles.emptyText}>No guide content available</Text>
        </View>
      </SafeAreaView>
    );
  }

  const { content } = currentGuide;

  return (
    <SafeAreaView style={styles.container}>
      <Header
        showBack
        onBack={() => navigation.goBack()}
        title="Your Guide"
        rightAction={
          <TouchableOpacity onPress={handleShare} style={styles.shareButton}>
            <Text style={styles.shareIcon}>📤</Text>
          </TouchableOpacity>
        }
      />

      <ScrollView
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Guide Header */}
        <View style={styles.guideHeader}>
          <Text style={styles.guideTitle}>{content.title}</Text>
          <Text style={styles.guideCity}>{currentGuide.city}</Text>
        </View>

        {/* Table of Contents */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>📋 Table of Contents</Text>
          <View style={styles.tocList}>
            <Text style={styles.tocItem}>1. Overview</Text>
            <Text style={styles.tocItem}>2. Recommended Hospitals</Text>
            <Text style={styles.tocItem}>3. Step-by-Step Process</Text>
            <Text style={styles.tocItem}>4. Cost Estimates</Text>
            <Text style={styles.tocItem}>5. Transportation</Text>
            <Text style={styles.tocItem}>6. Tips & Notes</Text>
          </View>
        </View>

        {/* Overview */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>1. Overview</Text>
          <Text style={styles.overviewText}>{content.overview}</Text>
        </View>

        {/* Recommended Hospitals */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>2. Recommended Hospitals</Text>
          {content.hospitals.map((hospital) => (
            <HospitalCard
              key={hospital.id}
              name={hospital.name}
              nameChinese={hospital.nameChinese}
              specialties={hospital.specialties}
              rating={hospital.rating}
              jciCertified={hospital.jciCertified}
              internationalDepartment={hospital.internationalDepartment}
              imageUrl={hospital.imageUrl}
            />
          ))}
        </View>

        {/* Step-by-Step Process */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>3. Step-by-Step Process</Text>
          {content.process.map((step, index) => (
            <View key={index} style={styles.processStep}>
              <View style={styles.stepNumber}>
                <Text style={styles.stepNumberText}>{step.step}</Text>
              </View>
              <View style={styles.stepContent}>
                <Text style={styles.stepTitle}>{step.title}</Text>
                <Text style={styles.stepDescription}>{step.description}</Text>
                {step.duration && (
                  <Text style={styles.stepDuration}>⏱ {step.duration}</Text>
                )}
                {step.tips && step.tips.length > 0 && (
                  <View style={styles.tipsContainer}>
                    {step.tips.map((tip, tipIndex) => (
                      <Text key={tipIndex} style={styles.tipItem}>
                        • {tip}
                      </Text>
                    ))}
                  </View>
                )}
              </View>
            </View>
          ))}
        </View>

        {/* Cost Estimates */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>4. Cost Estimates</Text>
          <View style={styles.costTable}>
            <View style={styles.costHeader}>
              <Text style={styles.costHeaderText}>Service</Text>
              <Text style={styles.costHeaderText}>Cost Range</Text>
            </View>
            {content.costs.map((cost, index) => (
              <View key={index} style={styles.costRow}>
                <Text style={styles.costService}>{cost.service}</Text>
                <Text style={styles.costValue}>
                  {cost.minCost}-{cost.maxCost} {cost.currency}
                </Text>
              </View>
            ))}
          </View>
        </View>

        {/* Transportation */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>5. Transportation</Text>
          <View style={styles.transportCard}>
            <View style={styles.transportItem}>
              <Text style={styles.transportLabel}>From Airport</Text>
              <Text style={styles.transportValue}>{content.transportation.fromAirport}</Text>
            </View>
            <View style={styles.transportItem}>
              <Text style={styles.transportLabel}>To Hospital</Text>
              <Text style={styles.transportValue}>{content.transportation.toHospital}</Text>
            </View>
            <View style={styles.transportItem}>
              <Text style={styles.transportLabel}>Estimated Cost</Text>
              <Text style={styles.transportValue}>{content.transportation.estimatedCost}</Text>
            </View>
          </View>
        </View>

        {/* Tips & Notes */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>6. Tips & Notes</Text>
          <View style={styles.tipsCard}>
            {content.tips.map((tip, index) => (
              <View key={index} style={styles.tipRow}>
                <Text style={styles.tipBullet}>✓</Text>
                <Text style={styles.tipText}>{tip}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Emergency Contacts */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>🚨 Emergency Contacts</Text>
          <View style={styles.emergencyCard}>
            {content.emergencyContacts.map((contact, index) => (
              <View key={index} style={styles.emergencyRow}>
                <Text style={styles.emergencyName}>{contact.name}</Text>
                <Text style={styles.emergencyNumber}>{contact.number}</Text>
              </View>
            ))}
          </View>
        </View>
      </ScrollView>

      {/* Bottom Actions */}
      <View style={styles.bottomContainer}>
        <Button
          title="Download PDF"
          onPress={handleDownload}
          variant="primary"
          size="large"
          style={styles.downloadButton}
        />
        <Button
          title="Share Guide"
          onPress={handleShare}
          variant="secondary"
          size="large"
          style={styles.shareGuideButton}
        />
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    fontSize: typography.body,
    color: colors.textSecondary,
  },
  scrollContent: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: 120,
  },
  shareButton: {
    padding: spacing.sm,
  },
  shareIcon: {
    fontSize: 20,
  },
  guideHeader: {
    marginBottom: spacing.xl,
  },
  guideTitle: {
    fontSize: typography.h2,
    fontWeight: typography.fontWeight.bold,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  guideCity: {
    fontSize: typography.body,
    color: colors.textSecondary,
  },
  section: {
    marginBottom: spacing.xl,
  },
  sectionTitle: {
    fontSize: typography.h3,
    fontWeight: typography.fontWeight.semiBold,
    color: colors.textPrimary,
    marginBottom: spacing.md,
  },
  tocList: {
    backgroundColor: colors.background,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
  },
  tocItem: {
    fontSize: typography.body,
    color: colors.textPrimary,
    marginBottom: spacing.sm,
  },
  overviewText: {
    fontSize: typography.body,
    color: colors.textSecondary,
    lineHeight: typography.lineHeight.body,
  },
  processStep: {
    flexDirection: 'row',
    marginBottom: spacing.md,
  },
  stepNumber: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primaryRed,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  stepNumberText: {
    fontSize: typography.body,
    fontWeight: typography.fontWeight.bold,
    color: colors.white,
  },
  stepContent: {
    flex: 1,
  },
  stepTitle: {
    fontSize: typography.body,
    fontWeight: typography.fontWeight.semiBold,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  stepDescription: {
    fontSize: typography.body,
    color: colors.textSecondary,
    marginBottom: spacing.sm,
  },
  stepDuration: {
    fontSize: typography.bodySmall,
    color: colors.textLight,
    marginBottom: spacing.sm,
  },
  tipsContainer: {
    backgroundColor: colors.background,
    borderRadius: borderRadius.md,
    padding: spacing.sm,
  },
  tipItem: {
    fontSize: typography.bodySmall,
    color: colors.textSecondary,
    marginBottom: spacing.xs,
  },
  costTable: {
    backgroundColor: colors.background,
    borderRadius: borderRadius.lg,
    overflow: 'hidden',
  },
  costHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: spacing.md,
    backgroundColor: colors.trustBlue,
  },
  costHeaderText: {
    fontSize: typography.bodySmall,
    fontWeight: typography.fontWeight.semiBold,
    color: colors.white,
  },
  costRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  costService: {
    fontSize: typography.body,
    color: colors.textPrimary,
  },
  costValue: {
    fontSize: typography.body,
    fontWeight: typography.fontWeight.medium,
    color: colors.primaryRed,
  },
  transportCard: {
    backgroundColor: colors.background,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
  },
  transportItem: {
    marginBottom: spacing.md,
  },
  transportLabel: {
    fontSize: typography.bodySmall,
    color: colors.textSecondary,
    marginBottom: spacing.xs,
  },
  transportValue: {
    fontSize: typography.body,
    color: colors.textPrimary,
  },
  tipsCard: {
    backgroundColor: colors.background,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
  },
  tipRow: {
    flexDirection: 'row',
    marginBottom: spacing.sm,
  },
  tipBullet: {
    fontSize: typography.body,
    color: colors.successGreen,
    marginRight: spacing.sm,
  },
  tipText: {
    flex: 1,
    fontSize: typography.body,
    color: colors.textPrimary,
  },
  emergencyCard: {
    backgroundColor: colors.errorRed + '10',
    borderRadius: borderRadius.lg,
    padding: spacing.md,
  },
  emergencyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  emergencyName: {
    fontSize: typography.body,
    color: colors.textPrimary,
  },
  emergencyNumber: {
    fontSize: typography.body,
    fontWeight: typography.fontWeight.bold,
    color: colors.errorRed,
  },
  bottomContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: spacing.xl,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
  downloadButton: {
    width: '100%',
    marginBottom: spacing.sm,
  },
  shareGuideButton: {
    width: '100%',
  },
});

export default GuideDisplayScreen;
